# code to create db and schema and to fill it with some data

from QA_final_project import db
from models import Academics, Papers, Authors

db.drop_all()
db.create.all()



#add some code here to create data to look at
academic1 = Academics('Bob Dole', 'University of Bradford', 'Metaphysics')
academic2 = Academics('Gisela Joseph','Zombie College', 'Magic History' )
academic3 = Academics('Durga Van As', 'Unseen University', 'Foreign Life Gardening')
academic4 = Academics('Nerva Augustus', 'University of Ithica', 'Hermetic Semiosis')
academic5 = Academics('Antoninus Pius', 'GURPS Illuminati University', 'Illumanti History')
academic6 = Academics('Narciso Baumann', 'Unseen University', 'English Literature')
academic7 = Academics('Trajan Augustus', 'University of Bradford', 'Dutch Ethnic Etymology')
academic8 = Academics('Captain Ahab','Zombie College', 'Hermetic Semiosis')
academic9 = Academics('Luke Skywalker','Zombie College','Metaphysics')
academic10 = Academics('Darth Vader', 'GURPS Illuminati University', 'Dutch Ethnic Etymology')
academic11 = Academics('Luitenent Starbuck', 'Unseen University', 'Illumanti History')
academic12 = Academics('Marcus Aurelius', 'University of Bradford', 'Hermetic Semiosis')
academic13 = Academics('Hadrian Augustus', 'GURPS Illuminati University', 'Dutch Ethnic Etymology')
academic14 = Academics('Hector Salamancis', 'Unseen University', 'Foreign Life Gardening')
academic15 = Academics('Noble Johnson', 'Starfleet Academy', 'English Literature')
academic16 = Academics('Augustus Ceaser', 'University of Ithica', 'Dutch Ethnic Etymology')
academic17 = Academics('Heracleus Ceaser','Zombie College', 'Illumanti History')
academic18 = Academics('Count Belisarius', 'Unseen University', 'Magic History')
academic19 = Academics('Cyrus The Great', 'Starfleet Academy', 'South Carribean Semiotics')
academic20 = Academics('Scipio Africanus', 'University of Ithica', 'Foreign Life Gardening')

paper1 = Papers('Nihilism and dialectic appropriation', 1985, 'Advanced Semiotics')
paper2 = Papers('Marxist capitalism in the works of Gaiman', 2020, 'The Occult')
paper3 = Papers('Postpatriarchial libertarianism in the works of Glass', 2010, 'Compter Science and Etymology')
paper4 = Papers('Postpatriarchial libertarianism in the works of Glass', 1999, 'Music and the Movement of the Spheres')
paper5 = Papers('Reinventing Constructivism: Modernism in the works of Eco', 2018, 'Semiotics and history of Evolution')
paper6 = Papers('A Biography of Eric "Eazy-E" Wright', 1998, 'Biography as the Expression of Power')
paper7 = Papers('The Principle Knowledge That God Is Omniscience', 2022, 'Mathematics of the Celestial Heavens')
paper8 = Papers('An Introduction to the Analysis of Theological Task', 2020, 'Ancient Astronauts')
paper9 = Papers('Precapitalist constructivist theory and postdeconstructive appropriation', 2006, 'Creationist Cosmologies')
paper10 = Papers('Precapitalist dematerialism and constructivism', 1970, 'The Occult')
paper11= Papers('Sartreist absurdity in the works of Gaiman', 1696, 'Advanced Semiotics')
paper12 = Papers('Examining the QCD Law in Models of Monopoles: Firewalls', 1066, 'Creationist Cosmologies') 
paper13 = Papers('Reflexive tactics for algebra, revisited', 1453, 'Ancient Astronauts')
paper14 = Papers('Evolution of SASyLF 2008-2021', 453, 'Biography as the Expression of Power')
paper15 = Papers('Bunched Fuzz: Sensitivity for Vector Metrics', 2001, 'Biography as the Expression of Power')
paper16 = Papers('Worlds of the Phaedo and the Term', 1875, 'Biography as the Expression of Power')
paper17 = Papers('Dark Spirituality as a Symbol Female', 1930, 'Creationist Cosmologies')
paper18 = Papers('Which can Jump Highe, a Car Flea of a Dog Flea?', 2010, 'Music and the Movement of the Spheres')
paper19 = Papers('Do Woodpeckers get Headaches?', 2006, 'Mathematics of the Celestial Heavens')
paper20 = Papers('The propulsion Paramters of Penguin Poop', 2008, 'Ancient Astronauts')

bridge1 = Authors(academic1.id, paper7.id)
bridge2 = Authors(academic2.id, paper7.id)
bridge3 = Authors(academic3.id, paper5.id)
bridge4 = Authors(academic4.id, paper3.id)
bridge5 = Authors(academic5.id, paper19.id)
bridge6 = Authors(academic6.id, paper9.id)
bridge7 = Authors(academic7.id, paper8.id)
bridge8 = Authors(academic8.id, paper4.id)
bridge9 = Authors(academic9.id, paper20.id)
bridge10 = Authors(academic10.id, paper19.id)
bridge11 = Authors(academic11.id, paper18.id)
bridge12 = Authors(academic12.id, paper17.id) 
bridge13 = Authors(academic13.id, paper16.id)
bridge14 = Authors(academic14.id, paper15.id)
bridge15 = Authors(academic15.id, paper14.id)
bridge16 = Authors(academic16.id, paper13.id)
bridge17 = Authors(academic17.id, paper12.id)
bridge18 = Authors(academic12.id, paper11.id)
bridge19 = Authors(academic19.id, paper10.id)
bridge20 = Authors(academic20.id, paper9.id)
bridge21 = Authors(academic2.id, paper8.id)
bridge22 = Authors(academic18.id, paper7.id)
bridge23 = Authors(academic4.id, paper6.id)
bridge24 = Authors(academic7.id, paper5.id)
bridge25 = Authors(academic12.id, paper4.id)
bridge26 = Authors(academic20.id, paper3.id)
bridge27 = Authors(academic1.id, paper2.id)
bridge28 = Authors(academic4.id, paper1.id)





db.session.add()
db.session.commit()