# code to create db and schema and to fill it with some data

from QA_final_project import db
from models import Academics, Papers, Authors

db.drop_all()
db.create.all()


#add some code here to create data to look at
academic = Academics('Bob Dole', 'University of Bradford', 'Metaphysics')
academic = Academics('Gisela Joseph','Zombie College', 'Magic History' )
academic = Academics('Durga Van As', 'Unseen University', 'Foreign Life Gardening')
academic = Academics('Nerva Augustus', 'University of Ithica', 'Hermetic Semiosis')
academic = Academics('Antoninus Pius', 'GURPS Illuminati University', 'Illumanti History')
academic = Academics('Narciso Baumann', 'Unseen University', 'English Literature')
academic = Academics('Trajan Augustus', 'University of Bradford', 'Dutch Ethnic Etymology')
academic = Academics('Captain Ahab','Zombie College', 'Hermetic Semiosis')
academic = Academics('Luke Skywalker','Zombie College','Metaphysics')
academic = Academics('Darth Vader', 'GURPS Illuminati University', 'Dutch Ethnic Etymology')
academic = Academics('Luitenent Starbuck', 'Unseen University', 'Illumanti History')
academic = Academics('Marcus Aurelius', 'University of Bradford', 'Hermetic Semiosis')
academic = Academics('Hadrian Augustus', 'GURPS Illuminati University', 'Dutch Ethnic Etymology')
academic = Academics('Hector Salamancis', 'Unseen University', 'Foreign Life Gardening')
academic = Academics('Noble Johnson', 'Starfleet Academy', 'English Literature')
academic = Academics('Augustus Ceaser', 'University of Ithica', 'Dutch Ethnic Etymology')
academic = Academics('Heracleus Ceaser','Zombie College', 'Illumanti History')
academic = Academics('Count Belisarius', 'Unseen University', 'Magic History')
academic = Academics('Cyrus The Great', 'Starfleet Academy', 'South Carribean Semiotics')
academic = Academics('Scipio Africanus', 'University of Ithica', 'Foreign Life Gardening')

paper = Papers('Nihilism and dialectic appropriation', 1985, 'Advanced Semiotics')
paper = Papers('Marxist capitalism in the works of Gaiman', 2020, 'The Occult')
paper = Papers('Postpatriarchial libertarianism in the works of Glass', 2010, 'Compter Science and Etymology')
paper = Papers('Postpatriarchial libertarianism in the works of Glass', 1999, 'Music and the Movement of the Spheres')
paper = Papers('Reinventing Constructivism: Modernism in the works of Eco', 2018, 'Semiotics and history of Evolution')
paper = Papers('A Biography of Eric "Eazy-E" Wright', 1998, 'Biography as the Expression of Power')
paper = Papers('The Principle Knowledge That God Is Omniscience', 2022, 'Mathematics of the Celestial Heavens')
paper = Papers('An Introduction to the Analysis of Theological Task', 2020, 'Ancient Astronauts')
paper = Papers('Precapitalist constructivist theory and postdeconstructive appropriation', 2006, 'Creationist Cosmologies')
paper = Papers('Precapitalist dematerialism and constructivism', 1970, 'The Occult')
paper = Papers('Sartreist absurdity in the works of Gaiman', 1696, 'Advanced Semiotics')
paper = Papers('Examining the QCD Law in Models of Monopoles: Firewalls', 1066, 'Creationist Cosmologies') 
paper = Papers('Reflexive tactics for algebra, revisited', 1453, 'Ancient Astronauts')
paper = Papers('Evolution of SASyLF 2008-2021', 453, 'Biography as the Expression of Power')
paper = Papers('Bunched Fuzz: Sensitivity for Vector Metrics', 2001, 'Biography as the Expression of Power')
paper = Papers('Worlds of the Phaedo and the Term', 1875, 'Biography as the Expression of Power')
paper = Papers('Dark Spirituality as a Symbol Female', 1930, 'Creationist Cosmologies')
paper = Papers('Which can Jump Highe, a Car Flea of a Dog Flea?', 2010, 'Music and the Movement of the Spheres')
paper = Papers('Do Woodpeckers get Headaches?', 2006, 'Mathematics of the Celestial Heavens')
paper = Papers('The propulsion Paramters of Penguin Poop', 2008, 'Ancient Astronauts')
