pipeline {
    agent any
    environment {
        SECRET_KEY = credentials('SECRET_KEY')
        DATABASE_URI = credentials('DATABASE_URI')
        APP_RUN = True
    }

    stages {
        stage('Setup') {
            steps {
                sh """sudo apt install python3-venv -y
                python3 -m venv venv
                . ./venv/bin/activate
                pip3 install -r requirements.txt
                sudo apt-get update
                sudo apt install curl -y
                curl https://get.docker.com | sudo bash
                sudo usermod -aG docker jenkins
                sudo systemctl restart jenkins
                """
            }
        }
        stage('Test') {
            steps {
                sh""" /home/jenkins/.jenkins/workspace/pipeline/venv/python3 -m pytest --junitxml unittests.xml
                /home/jenkins/.jenkins/workspace/pipeline/venv/python3 -m pytest --cov-report xml:coverage.xml""" 

            }
        }
        stage('Build') {
            steps {sh"""docker build -t myapp ."""

            }
        }
        stage('Deploy') {
            steps {
                if (APP_RUN == true) {
                sh """docker run --name myapp -e DATABASE_URI=sqlite:///data.db -e SECRET_KEY=abcd -d -p 5000:5000 myapp"""
                }
            }
        }
        stage('post build') {
            steps{
                junit 'unittests.xml'
                cobertura autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'coverage.xml', conditionalCoverageTargets: '70, 0, 0', failUnhealthy: false, failUnstable: false, lineCoverageTargets: '80, 0, 0', maxNumberOfBuilds: 0, methodCoverageTargets: '80, 0, 0', onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false
archiveArtifacts artifacts: '*.xml', followSymlinks: false
                
            }
        }
    }   
}
