pipeline {
    agent any
    environment {
        SECRET_KEY = credentials('SECRET_KEY')
        DATABASE_URI = credentials('DATABASE_URI')
        //DOCKER_LOGIN = credentials('DOCKERHUB')
        SQLPWD= credentials('SQLPWD')
        DATABASE_URI_CREATE = credentials('DATABASE_URI_CREATE')
        APP_RUN = 'True'
    }

    stages {
        stage('Setup') {
            steps {
                sh """sudo apt install python3-venv -y 
                python3 -m venv venv
                . ./venv/bin/activate
                pip3 install -r requirements.txt
                """
            }
        }
/*
        stage('Test') {
            steps {
                sh """ . ./venv/bin/activate
                python3 -m pytest --junitxml unittests.xml
                python3 -m pytest --cov-report xml:coverage.xml""" 

            }
        }

        stage('login') {
            steps {
                sh 'echo $DOCKER_LOGIN_PSW | docker login -u $DOCKER_LOGIN_USR --password-stdin'
            }
        }*/

        stage('docker-compose') {
            steps {
                sh "docker-compose up -d"
            }
        }
         stage('create database') {
            steps {
                sh"docker exec myapp -c 'usr/bin/python3; create.py'"
            }
}
/*        stage('Build') {
            steps {
                sh """docker build -t corcoran909/myapp ."""
            }
        }

        stage('push'){
            steps{
                sh 'docker push corcoran909/myapp:latest'
            }
        }*/
/*
        stage('Deploy') {
            steps {
                sh """
                docker rm -f myapp
                docker run --network mynetwork --name myapp -d -p 5000:5000 corcoran909/myapp
                """
            }
        }
        
        stage('post build') {
            steps{
                junit 'unittests.xml'
                cobertura autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'coverage.xml', conditionalCoverageTargets: '70, 0, 0', failUnhealthy: false, failUnstable: false, lineCoverageTargets: '80, 0, 0', maxNumberOfBuilds: 0, methodCoverageTargets: '80, 0, 0', onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false
archiveArtifacts artifacts: '*.xml', followSymlinks: false
                
            }
        }*/
    }   
}
