pipeline {
    agent any
    environment {
        SECRET_KEY = credentials('DATABASE_URI')
        DATABASE_URI = credentials('SECRET_KEY')
        APP_RUN = True
    }

    stages {
        stage('Build') {
            steps {
                sh """sudo apt install python3-venv -y
                python3 -m venv venv
                . ./venv/bin/activate
                pip3 install -r requirements.txt"""
            }
        }
        stage('Test') {
            steps {
                sh""" /home/jenkins/.jenkins/workspace/pipeline/venv/python3 -m pytest --junitxml unittests.xml
                /home/jenkins/.jenkins/workspace/pipeline/venv/python3 -m pytest --cov-report xml:coverage.xml""" 

            }
        }
        stage('Deploy') {
            steps {
                sh """python3 create.py
                python3 app.py"""
            }
        }
        stage('post build') {
            steps{
                junit 'unittest.xml'
                cobertura coberturaReportFile: 'coverage.xml'
            }
        }
    }   
}
